Add Outputs to Update Workflow
getsentry/github-workflows pull request #18
Opened 2022-08-01 14:21 UTC by denrase

This PR adds the following outputs to the update workflow:

- url
- original tag
- latest tag
- base branch
- pr branch

This way, other repositories can pick up the created PR and amend it as they see fit. 

An example can be seen here:

https://github.com/getsentry/sentry-fastlane-plugin/pull/144

The referenced PR takes the created/updated PR, downloads the current sentry-cli macOS & windows binaries and commits them in the PR created by this workflow.
It does not use the `url` and `base branch` outputs, but i left those as they might be useful for other approaches.

2022-08-01 14:32 UTC, vaind requested changes

2022-08-01 14:32 UTC, vaind commented on .github/workflows/updater.yml
> +      url:
`url` is a bit too generic, maybe `prUrl`, which is in line with `prBranch` suggested below.
```suggestion
      prUrl:
```

2022-08-01 14:32 UTC, vaind commented on .github/workflows/updater.yml
> +      url: ${{ steps.pr.outputs.url }}
```suggestion
      prUrl: ${{ steps.pr.outputs.url }}
```

2022-08-01 14:45 UTC, vaind approved these changes

2022-08-01 14:45 UTC, merged

2022-08-02 11:21 UTC, denrase commented
🥳